### ISSUE TITLE
OpenApiRuntimeHint.class

### ISSUE THREAD

**Issue by williamspindox** [MaheshBabu11/ChatGPTClone#1]
I've a class not found for @ImportRuntimeHints(value = {OpenApiRuntimeHint.class})
How can I fix it? thanks

**Comment by MaheshBabu11** [comment]
You can remove it from the application main class and use it like this instead

```
@SpringBootApplication
@Theme(value = "spring-boot-react-springai-chatgpt")
public class Application implements AppShellConfigurator {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

```

I have added that for native graalVm support and failed to remove it here. it is used to generate run-time hints while using AOT. If needed I will add it here as well

```
package com.maheshbabu11;

import com.theokanning.openai.client.OpenAiApi;
import org.springframework.aot.hint.ProxyHints;
import org.springframework.aot.hint.RuntimeHints;
import org.springframework.aot.hint.RuntimeHintsRegistrar;

public class OpenApiRuntimeHint implements RuntimeHintsRegistrar {

    @Override
    public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
        try {
            ProxyHints proxies = hints.proxies();
            proxies.registerJdkProxy(OpenAiApi.class);
        } catch (Exception e) {
            throw new RuntimeException("Could not register RuntimeHint: " + e.getMessage());
        }
    }

}
```

**Comment by williamspindox** [comment]
Ok thank you. It would be great an example with HuggingfaceAiClient too.
Anyway I'm having trouble starting current UI with Springboot:

Vaadin is running in DEVELOPMENT mode - do not use for production deployments.
[2m2024-01-12T12:56:09.300+01:00[0;39m [32m INFO[0;39m [35m25280[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mo.s.b.w.embedded.tomcat.TomcatWebServer [0;39m [2m:[0;39m Tomcat started on port(s): 8080 (http) with context path ''
[2m2024-01-12T12:56:09.308+01:00[0;39m [32m INFO[0;39m [35m25280[0;39m [2m---[0;39m [2m[  restartedMain][0;39m [36mcom.maheshbabu11.Application            [0;39m [2m:[0;39m Started Application in 23.403 seconds (process running for 24.379)
[2m2024-01-12T12:56:09.895+01:00[0;39m [32m INFO[0;39m [35m25280[0;39m [2m---[0;39m [2m[nio-8080-exec-1][0;39m [36mo.a.c.c.C.[Tomcat].[localhost].[/]      [0;39m [2m:[0;39m Initializing Spring DispatcherServlet 'dispatcherServlet'
[2m2024-01-12T12:56:09.895+01:00[0;39m [32m INFO[0;39m [35m25280[0;39m [2m---[0;39m [2m[nio-8080-exec-1][0;39m [36mo.s.web.servlet.DispatcherServlet       [0;39m [2m:[0;39m Initializing Servlet 'dispatcherServlet'
[2m2024-01-12T12:56:09.896+01:00[0;39m [32m INFO[0;39m [35m25280[0;39m [2m---[0;39m [2m[nio-8080-exec-1][0;39m [36mo.s.web.servlet.DispatcherServlet       [0;39m [2m:[0;39m Completed initialization in 1 ms
[2m2024-01-12T12:56:09.940+01:00[0;39m [32m INFO[0;39m [35m25280[0;39m [2m---[0;39m [2m[nio-8080-exec-1][0;39m [36mc.vaadin.flow.spring.SpringInstantiator [0;39m [2m:[0;39m The number of beans implementing 'I18NProvider' is 0. Cannot use Spring beans for I18N, falling back to the default behavior
[2m2024-01-12T12:56:09.941+01:00[0;39m [31mERROR[0;39m [35m25280[0;39m [2m---[0;39m [2m[nio-8080-exec-1][0;39m [36mc.v.flow.server.DefaultErrorHandler     [0;39m [2m:[0;39m 

java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 58
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4602) ~[na:na]
	at java.base/java.lang.String.substring(String.java:2705) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.lambda$getCurrentJavaProcessJavaHome$2(CommandRunner.java:208) ~[engine-core-2.3.3.jar:na]
	at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.getCurrentJavaProcessJavaHome(CommandRunner.java:206) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.environment(CommandRunner.java:226) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.createProcessBuilder(CommandRunner.java:174) ~[engine-core-2.3.3.jar:na]
...

Regards,
